/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface Feature {
  'id' : bigint,
  'title' : string,
  'order' : bigint,
  'description' : string,
  'iconName' : string,
  'image' : ExternalBlob,
}
export interface HeroContent {
  'headline' : string,
  'backgroundImage' : ExternalBlob,
  'ctaLink' : string,
  'ctaText' : string,
  'subheadline' : string,
}
export interface Product {
  'id' : bigint,
  'featured' : boolean,
  'inStock' : boolean,
  'name' : string,
  'createdAt' : Time,
  'price_cents' : bigint,
  'description' : string,
  'category' : string,
  'image' : ExternalBlob,
}
export interface Testimonial {
  'id' : bigint,
  'authorAvatar' : ExternalBlob,
  'createdAt' : Time,
  'authorName' : string,
  'quote' : string,
  'rating' : bigint,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createFeature' : ActorMethod<[Feature], bigint>,
  'createProduct' : ActorMethod<[Product], bigint>,
  'createTestimonial' : ActorMethod<[Testimonial], bigint>,
  'deleteFeature' : ActorMethod<[bigint], undefined>,
  'deleteProduct' : ActorMethod<[bigint], undefined>,
  'deleteTestimonial' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFeaturedProducts' : ActorMethod<[], Array<Product>>,
  'getFeatures' : ActorMethod<[], Array<Feature>>,
  'getHeroContent' : ActorMethod<[], [] | [HeroContent]>,
  'getProduct' : ActorMethod<[bigint], Product>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateFeature' : ActorMethod<[bigint, Feature], undefined>,
  'updateHeroContent' : ActorMethod<[HeroContent], undefined>,
  'updateProduct' : ActorMethod<[bigint, Product], undefined>,
  'updateTestimonial' : ActorMethod<[bigint, Testimonial], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];